source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FullingSwiper_Example', :exclusive => true do
  pod 'FullingSwiper', :path => '../'
end

target 'FullingSwiper_Tests', :exclusive => true do
  pod 'FullingSwiper', :path => '../'

  pod 'FBSnapshotTestCase'
end
